### ISSUE TITLE
The chrome on the iPhone can't be used,

### ISSUE THREAD

**Issue by JYYM** [urish/webble-mip#2]
The chrome on the iPhone can't be used, and the "Web Bluetooth is disabled!" error is displayed.

**Comment by JYYM** [comment]
Doesn't support chrome on your phone?

**Comment by urish** [comment]
iPhone does not support Web Bluetooth at the moment, even in Chrome. You can see a full list of the supported platforms here: https://github.com/WebBluetoothCG/web-bluetooth/blob/master/implementation-status.md

And here is more information specifically about the iPhone: https://stackoverflow.com/questions/45745905/how-can-users-use-web-bluetooth-apps-on-ios
